package io.miragon.blueprint

import org.operaton.rest.client.api.MessageApi
import org.operaton.rest.client.api.ProcessInstanceApi
import org.operaton.rest.client.api.TaskApi
import org.springframework.beans.factory.annotation.Value
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.context.annotation.Bean
import org.springframework.web.client.RestClient
import java.time.Clock

/**
 * The remote worker + business logic. It hosts the domain, use cases and adapters, subscribes to the
 * engine's external service-tasks over the external-task client, and drives the process (start, user
 * tasks, messages) over the engine's REST API. The Operaton engine itself runs in `engine-service`.
 */
@SpringBootApplication
class ExampleServiceApplication {

    /** Single source of "now" for the app, so time-dependent logic can be pinned in tests. */
    @Bean
    fun clock(): Clock = Clock.systemDefaultZone()

    /**
     * [RestClient] pointed at the remote Operaton engine's REST API. It backs the autogenerated CIB
     * seven client APIs below and the multipart deployment adapter, so the base URL is configured once.
     */
    @Bean
    fun engineRestClient(
        @Value("\${bike-leasing.engine-rest-base-url}") baseUrl: String,
    ): RestClient = RestClient.builder()
        .baseUrl(baseUrl)
        .build()

    /** Autogenerated Operaton `/message` client — correlates messages that release the wait states. */
    @Bean
    fun messageApi(engineRestClient: RestClient): MessageApi = MessageApi(engineRestClient)

    /** Autogenerated Operaton `/task` client — queries and completes user tasks. */
    @Bean
    fun taskApi(engineRestClient: RestClient): TaskApi = TaskApi(engineRestClient)

    /** Autogenerated Operaton `/process-instance` client — resolves business keys for the task inbox. */
    @Bean
    fun processInstanceApi(engineRestClient: RestClient): ProcessInstanceApi = ProcessInstanceApi(engineRestClient)
}

fun main(args: Array<String>) {
    runApplication<ExampleServiceApplication>(*args)
}
