package io.miragon.blueprint.adapter.outbound.engine;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.annotation.Profile;
import org.springframework.context.event.EventListener;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;
import org.springframework.web.client.RestClient;

/**
 * Deploys the process model (owned and carried by this service, from its own {@code src/main/resources})
 * into the <strong>remote</strong> engine at start-up — the remote counterpart to the embedded engine's
 * classpath auto-deployment.
 *
 * <p>This realises the "the service owns and deploys its process" ownership pattern: the engine host
 * stays model-agnostic and this outbound adapter pushes its BPMN/DMN/forms to
 * {@code POST /engine-rest/deployment/create}. The deployment is <strong>idempotent</strong>
 * ({@code enable-duplicate-filtering} + {@code deploy-changed-only}), so restarts and multiple worker
 * instances never create duplicate deployments. It retries briefly so the worker can start alongside a
 * not-yet-ready engine.
 *
 * <p>(For the alternative "the engine owns the model" pattern — a shared process fulfilled by several
 * services — remove this bean and let the engine deploy from its own classpath; see the engine-service
 * README.)
 *
 * <p>Unlike the process-driving calls, this one stays on the hand-built {@link RestClient}:
 * {@code deployment/create} is a multipart upload of <strong>several</strong> files with dynamic
 * filenames, which the OpenAPI spec models as a single binary field — so the autogenerated client
 * cannot faithfully express it. This is the one documented exception to "drive the engine through the
 * generated client".
 */
@Component
@Profile("!test")
public class ProcessModelDeploymentAdapter {

    private static final String DEPLOYMENT_NAME = "bike-leasing";
    private static final List<String> MODEL_PATTERNS =
            List.of("classpath*:**/*.bpmn", "classpath*:**/*.dmn", "classpath*:**/*.form");
    private static final int MAX_ATTEMPTS = 20;
    private static final long RETRY_DELAY_MS = 3_000L;

    private static final Logger log = LoggerFactory.getLogger(ProcessModelDeploymentAdapter.class);

    private final RestClient engineRestClient;
    private final PathMatchingResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();

    public ProcessModelDeploymentAdapter(RestClient engineRestClient) {
        this.engineRestClient = engineRestClient;
    }

    @EventListener(ApplicationReadyEvent.class)
    public void deployProcessModel() throws IOException {
        List<Resource> resources = new ArrayList<>();
        for (String pattern : MODEL_PATTERNS) {
            for (Resource resource : resolver.getResources(pattern)) {
                resources.add(resource);
            }
        }
        if (resources.isEmpty()) {
            log.warn("No process resources found on the classpath — nothing to deploy");
            return;
        }
        for (int attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {
            try {
                deploy(resources);
                log.info("Deployed {} process resources to the remote engine: {}",
                        resources.size(), resources.stream().map(Resource::getFilename).filter(f -> f != null).toList());
                return;
            } catch (Exception e) {
                if (attempt == MAX_ATTEMPTS - 1) {
                    log.error("Could not deploy the process model after {} attempts — is the engine running?",
                            MAX_ATTEMPTS, e);
                    return;
                }
                log.warn("Engine not reachable yet (attempt {}/{}), retrying in {}ms",
                        attempt + 1, MAX_ATTEMPTS, RETRY_DELAY_MS);
                try {
                    Thread.sleep(RETRY_DELAY_MS);
                } catch (InterruptedException interrupted) {
                    Thread.currentThread().interrupt();
                    return;
                }
            }
        }
    }

    private void deploy(List<Resource> resources) {
        MultiValueMap<String, Object> body = new LinkedMultiValueMap<>();
        body.add("deployment-name", DEPLOYMENT_NAME);
        body.add("deployment-source", "example-service");
        body.add("enable-duplicate-filtering", "true");
        body.add("deploy-changed-only", "true");
        for (Resource resource : resources) {
            String filename = resource.getFilename();
            if (filename == null) {
                throw new IllegalStateException("classpath resource without a filename: " + resource);
            }
            body.add(filename, resource);
        }
        engineRestClient.post()
                .uri("/deployment/create")
                .contentType(MediaType.MULTIPART_FORM_DATA)
                .body(body)
                .retrieve()
                .toBodilessEntity();
    }
}
