package io.miragon.blueprint;

import java.time.Clock;
import org.operaton.rest.client.ApiClient;
import org.operaton.rest.client.api.MessageApi;
import org.operaton.rest.client.api.ProcessInstanceApi;
import org.operaton.rest.client.api.TaskApi;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.web.client.RestClient;

/**
 * The remote worker + business logic. It hosts the domain, use cases and adapters, subscribes to the
 * engine's external service-tasks over the external-task client, and drives the process (start, user
 * tasks, messages) over the engine's REST API. The Operaton engine itself runs in {@code engine-service}.
 */
@SpringBootApplication
public class ExampleServiceApplication {

    /** Single source of "now" for the app, so time-dependent logic can be pinned in tests. */
    @Bean
    public Clock clock() {
        return Clock.systemDefaultZone();
    }

    /**
     * {@link RestClient} pointed at the remote Operaton engine's REST API. It backs the multipart
     * deployment adapter, so the base URL is configured once.
     */
    @Bean
    public RestClient engineRestClient(@Value("${bike-leasing.engine-rest-base-url}") String baseUrl) {
        return RestClient.builder()
                .baseUrl(baseUrl)
                .build();
    }

    /**
     * Autogenerated-client {@link ApiClient}, pointed at the remote engine's REST API. It backs the
     * typed Operaton client APIs below (message, task, process-instance).
     */
    @Bean
    public ApiClient engineApiClient(@Value("${bike-leasing.engine-rest-base-url}") String baseUrl) {
        return new ApiClient().setBasePath(baseUrl);
    }

    /** Autogenerated Operaton {@code /message} client — correlates messages that release the wait states. */
    @Bean
    public MessageApi messageApi(ApiClient engineApiClient) {
        return new MessageApi(engineApiClient);
    }

    /** Autogenerated Operaton {@code /task} client — queries and completes user tasks. */
    @Bean
    public TaskApi taskApi(ApiClient engineApiClient) {
        return new TaskApi(engineApiClient);
    }

    /** Autogenerated Operaton {@code /process-instance} client — resolves business keys for the task inbox. */
    @Bean
    public ProcessInstanceApi processInstanceApi(ApiClient engineApiClient) {
        return new ProcessInstanceApi(engineApiClient);
    }

    public static void main(String[] args) {
        SpringApplication.run(ExampleServiceApplication.class, args);
    }
}
