plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.openapiGenerator)
}

/**
 * Autogenerated Operaton engine REST client.
 *
 * Hand-writing REST calls against `/engine-rest` is error-prone, so this module generates a complete,
 * typed client from Operaton's *official* OpenAPI document, which ships (as `openapi.json` at the jar
 * root) inside the `operaton-engine-rest-openapi` artifact. That artifact is pinned to the engine
 * version (`operaton_version`), so client and engine never drift.
 *
 * Build flow: resolve the spec artifact -> extract the bundled `openapi.json` -> run the OpenAPI
 * Generator (Kotlin + `jvm-spring-restclient`, matching the `RestClient` the worker already uses) ->
 * compile the generated sources. Nothing generated is committed; it is a build artifact under `build/`.
 */

val operatonOpenApiSpec: Configuration by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
}

dependencies {
    // Resolve *only* the openapi artifact — Operaton's `operaton-engine-rest-openapi` declares
    // transitive dependencies, and we just need the jar that bundles `openapi.json` at its root.
    operatonOpenApiSpec(libs.operaton.rest.openapi) { isTransitive = false }

    api(platform("org.springframework.boot:spring-boot-dependencies:${libs.versions.spring.version.get()}"))
    api("org.springframework:spring-web")
    api(libs.jackson.kotlin)
    api(libs.jakarta.annotation.api)
    implementation(libs.kotlin.reflect)
}

val extractOpenApiSpec by tasks.registering(Sync::class) {
    from(provider { zipTree(operatonOpenApiSpec.singleFile) }) { include("**/openapi.json") }
    eachFile { relativePath = RelativePath(true, name) }
    includeEmptyDirs = false
    into(layout.buildDirectory.dir("openapi"))
}

openApiGenerate {
    generatorName.set("kotlin")
    library.set("jvm-spring-restclient")
    inputSpec.set(layout.buildDirectory.file("openapi/openapi.json").get().asFile.path)
    outputDir.set(layout.buildDirectory.dir("generated/openapi").get().asFile.path)
    packageName.set("org.operaton.rest.client")
    apiPackage.set("org.operaton.rest.client.api")
    modelPackage.set("org.operaton.rest.client.model")
    validateSpec.set(false)
    configOptions.set(
        mapOf(
            "serializationLibrary" to "jackson",
            "useSpringBoot3" to "true",
            "enumPropertyNaming" to "UPPERCASE",
        ),
    )
}

tasks.named("openApiGenerate") { dependsOn(extractOpenApiSpec) }

kotlin.sourceSets["main"].kotlin.srcDir(layout.buildDirectory.dir("generated/openapi/src/main/kotlin"))

tasks.named("compileKotlin") { dependsOn("openApiGenerate") }

java {
    sourceCompatibility = JavaVersion.VERSION_21
}
