// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.blueprint.process

import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

/**
 * Job worker task types used in `@JobWorker(type = ServiceTasks.X)` annotations.
 * Kept as `const val String` because annotation arguments must be compile-time constants.
 */
object ServiceTasks {
  const val BIKE_LEASING_ACTIVATE_LEASING: String = "bikeLeasing.activateLeasing"

  const val BIKE_LEASING_BOOK_COSTS: String = "bikeLeasing.bookCosts"

  const val BIKE_LEASING_CANCEL_CONTRACT: String = "bikeLeasing.cancelContract"

  const val BIKE_LEASING_CANCEL_POLICY: String = "bikeLeasing.cancelPolicy"

  const val BIKE_LEASING_ISSUE_INSURANCE_POLICY: String = "bikeLeasing.issueInsurancePolicy"

  const val BIKE_LEASING_ORDER_BIKE: String = "bikeLeasing.orderBike"

  const val BIKE_LEASING_REQUEST_CANCELLATION: String = "bikeLeasing.requestCancellation"

  const val BIKE_LEASING_SEND_CANCELLATION_CONFIRMATION: String =
      "bikeLeasing.sendCancellationConfirmation"

  const val BIKE_LEASING_SEND_CONTRACT: String = "bikeLeasing.sendContract"

  const val BIKE_LEASING_SEND_REJECTION: String = "bikeLeasing.sendRejection"

  const val BIKE_LEASING_SEND_REMINDER_MAIL: String = "bikeLeasing.sendReminderMail"

  const val BIKE_LEASING_VALIDATE_APPLICATION: String = "bikeLeasing.validateApplication"

  val all: List<String> = listOf(
    BIKE_LEASING_ACTIVATE_LEASING,
    BIKE_LEASING_BOOK_COSTS,
    BIKE_LEASING_CANCEL_CONTRACT,
    BIKE_LEASING_CANCEL_POLICY,
    BIKE_LEASING_ISSUE_INSURANCE_POLICY,
    BIKE_LEASING_ORDER_BIKE,
    BIKE_LEASING_REQUEST_CANCELLATION,
    BIKE_LEASING_SEND_CANCELLATION_CONFIRMATION,
    BIKE_LEASING_SEND_CONTRACT,
    BIKE_LEASING_SEND_REJECTION,
    BIKE_LEASING_SEND_REMINDER_MAIL,
    BIKE_LEASING_VALIDATE_APPLICATION,
  )
}
