package io.miragon.blueprint.adapter.outbound.engine;

import static io.miragon.blueprint.domain.leasing.TestObjectBuilder.testLeasingApplication;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.catchThrowable;
import static org.hamcrest.Matchers.containsString;
import static org.springframework.test.web.client.match.MockRestRequestMatchers.jsonPath;
import static org.springframework.test.web.client.match.MockRestRequestMatchers.method;
import static org.springframework.test.web.client.match.MockRestRequestMatchers.requestTo;
import static org.springframework.test.web.client.response.MockRestResponseCreators.withSuccess;

import io.miragon.blueprint.domain.bike.BikeId;
import io.miragon.blueprint.domain.leasing.LeasingApplication;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.operaton.rest.client.ApiClient;
import org.operaton.rest.client.api.MessageApi;
import org.operaton.rest.client.api.TaskApi;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.test.web.client.MockRestServiceServer;
import org.springframework.web.client.RestClient;

/**
 * Verifies the outbound adapter speaks the expected Operaton REST dialect: the {@code ApplicationId} is
 * used as the business key, the message-start carries typed process variables, and the user task is
 * looked up by business key before being completed. This is also the regression guard proving the
 * autogenerated client emits the expected wire format.
 */
class RemoteLeasingProcessAdapterTest {

    private MockRestServiceServer server;
    private RemoteLeasingProcessAdapter underTest;

    @BeforeEach
    void setUp() {
        RestClient.Builder builder = RestClient.builder();
        server = MockRestServiceServer.bindTo(builder).build();
        ApiClient apiClient = new ApiClient(builder.build()).setBasePath("http://engine/engine-rest");
        underTest = new RemoteLeasingProcessAdapter(new MessageApi(apiClient), new TaskApi(apiClient));
    }

    @Test
    void submitRequestStartsTheProcessViaItsMessageStartEventWithTypedVariables() {

        // given: a valid application and an engine that accepts the start message
        LeasingApplication application = testLeasingApplication().build();
        server.expect(requestTo("http://engine/engine-rest/message"))
                .andExpect(method(HttpMethod.POST))
                .andExpect(jsonPath("$.messageName").value("miravelo.leasingRequestReceived"))
                .andExpect(jsonPath("$.businessKey").value(application.id().value().toString()))
                .andExpect(jsonPath("$.processVariables.applicationId.value").value(application.id().value().toString()))
                .andExpect(jsonPath("$.processVariables.bikeId.value").value(application.bikeId().value()))
                .andExpect(jsonPath("$.processVariables.monthlyNetIncome.type").value("Double"))
                .andExpect(jsonPath("$.processVariables.age.type").value("Integer"))
                .andRespond(withSuccess("[]", MediaType.APPLICATION_JSON));

        // when: the request is submitted
        underTest.submitRequest(application);

        // then: exactly the expected call was made
        server.verify();
    }

    @Test
    void correlateHandoverReportedSendsTheMessageCorrelatedByBusinessKey() {

        // given: an engine that accepts the correlation
        LeasingApplication application = testLeasingApplication().build();
        server.expect(requestTo("http://engine/engine-rest/message"))
                .andExpect(method(HttpMethod.POST))
                .andExpect(jsonPath("$.messageName").value("miravelo.handoverReported"))
                .andExpect(jsonPath("$.businessKey").value(application.id().value().toString()))
                .andRespond(withSuccess("[]", MediaType.APPLICATION_JSON));

        // when: the handover-reported message is correlated
        underTest.correlateHandoverReported(application.id());

        // then: the message was sent
        server.verify();
    }

    @Test
    void correlateContractSignedSendsTheMessageCorrelatedByBusinessKey() {

        // given: an engine that accepts the correlation
        LeasingApplication application = testLeasingApplication().build();
        server.expect(requestTo("http://engine/engine-rest/message"))
                .andExpect(method(HttpMethod.POST))
                .andExpect(jsonPath("$.messageName").value("miravelo.contractSigned"))
                .andExpect(jsonPath("$.businessKey").value(application.id().value().toString()))
                .andRespond(withSuccess("[]", MediaType.APPLICATION_JSON));

        // when: the contract-signed message is correlated
        underTest.correlateContractSigned(application.id());

        // then: the message was sent
        server.verify();
    }

    @Test
    void completeAlternativeClarificationLooksUpTheTaskByBusinessKeyAndCompletesIt() {

        // given: one active clarify-alternative task for the application
        LeasingApplication application = testLeasingApplication().build();
        server.expect(requestTo("http://engine/engine-rest/task"))
                .andExpect(method(HttpMethod.POST))
                .andExpect(jsonPath("$.processInstanceBusinessKey").value(application.id().value().toString()))
                .andExpect(jsonPath("$.taskDefinitionKey").value("userTask_clarifyAlternative"))
                .andRespond(withSuccess("[{\"id\":\"task-1\"}]", MediaType.APPLICATION_JSON));
        server.expect(requestTo("http://engine/engine-rest/task/task-1/complete"))
                .andExpect(method(HttpMethod.POST))
                .andExpect(jsonPath("$.variables.alternativeFound.value").value(true))
                .andExpect(jsonPath("$.variables.bikeId.value").value("BIKE-100"))
                .andRespond(withSuccess());

        // when: the alternative is confirmed with a replacement bike
        underTest.completeAlternativeClarification(application.id(), true, new BikeId("BIKE-100"));

        // then: both the lookup and completion happened
        server.verify();
    }

    @Test
    void completeAlternativeClarificationFailsWhenNoActiveTaskExists() {

        // given: the engine reports no active task
        LeasingApplication application = testLeasingApplication().build();
        server.expect(requestTo(containsString("/task")))
                .andExpect(method(HttpMethod.POST))
                .andRespond(withSuccess("[]", MediaType.APPLICATION_JSON));

        // when / then: completing the clarification surfaces the missing task
        Throwable error = catchThrowable(() ->
                underTest.completeAlternativeClarification(application.id(), false, null));
        assertThat(error).isInstanceOf(IllegalStateException.class);
        server.verify();
    }
}
