// Generated by bpmn-to-code
package io.miragon.blueprint.process;

import io.miragon.bpmn.runtime.BpmnEngine;
import io.miragon.bpmn.runtime.BpmnError;
import io.miragon.bpmn.runtime.BpmnEscalation;
import io.miragon.bpmn.runtime.BpmnFlow;
import io.miragon.bpmn.runtime.BpmnRelations;
import io.miragon.bpmn.runtime.BpmnTimer;
import io.miragon.bpmn.runtime.ElementId;
import io.miragon.bpmn.runtime.InputOutputMapping;
import io.miragon.bpmn.runtime.MessageName;
import io.miragon.bpmn.runtime.ProcessId;
import io.miragon.bpmn.runtime.VariableName;
import java.lang.String;
import java.util.List;

public final class BikeLeasingProcessProcessApi {
  public static final ProcessId PROCESS_ID = new ProcessId("bikeLeasingProcess");

  public static final BpmnEngine PROCESS_ENGINE = BpmnEngine.CAMUNDA_7;

  /**
   * BPMN element ids as declared in the source model.
   * Typically used in process-level tests or when searching for tasks.
   * Worker runtime code rarely needs these.
   */
  public static final class Elements {
    public static final ElementId BUSINESS_RULE_TASK_CHECK_CREDIT_RATING = new ElementId("businessRuleTask_checkCreditRating");

    public static final ElementId CALL_ACTIVITY_CANCEL_BIKE_ORDER = new ElementId("callActivity_cancelBikeOrder");

    public static final ElementId END_EVENT_APPLICATION_CANCELLED = new ElementId("endEvent_applicationCancelled");

    public static final ElementId END_EVENT_APPLICATION_REJECTED = new ElementId("endEvent_applicationRejected");

    public static final ElementId END_EVENT_CONTRACT_CANCELLED = new ElementId("endEvent_contractCancelled");

    public static final ElementId END_EVENT_CONTRACT_VALID = new ElementId("endEvent_contractValid");

    public static final ElementId END_EVENT_LEASING_ACTIVE = new ElementId("endEvent_leasingActive");

    public static final ElementId END_EVENT_NOT_SIGNED = new ElementId("endEvent_notSigned");

    public static final ElementId END_EVENT_PROSPECT_REMINDED = new ElementId("endEvent_prospectReminded");

    public static final ElementId EVENT_APPLICATION_INVALID = new ElementId("event_applicationInvalid");

    public static final ElementId EVENT_COMPENSATE_CONTRACT = new ElementId("event_compensateContract");

    public static final ElementId EVENT_COMPENSATE_INSURANCE = new ElementId("event_compensateInsurance");

    public static final ElementId EVENT_COMPENSATE_ORDER = new ElementId("event_compensateOrder");

    public static final ElementId EVENT_CONTRACT_NOT_SIGNED = new ElementId("event_contractNotSigned");

    public static final ElementId EVENT_CONTRACT_SIGNED = new ElementId("event_contractSigned");

    public static final ElementId EVENT_HANDOVER_REPORTED = new ElementId("event_handoverReported");

    public static final ElementId EVENT_REVERSE_APPLICATION = new ElementId("event_reverseApplication");

    public static final ElementId EVENT_SIGNATURE_DEADLINE = new ElementId("event_signatureDeadline");

    public static final ElementId EVENT_SIGNATURE_REMINDER = new ElementId("event_signatureReminder");

    public static final ElementId EVENT_TRIGGER_REVERSAL = new ElementId("event_triggerReversal");

    public static final ElementId EVENT_WITHDRAWAL_PERIOD_ELAPSED = new ElementId("event_withdrawalPeriodElapsed");

    public static final ElementId GATEWAY_ALTERNATIVE_FOUND = new ElementId("gateway_alternativeFound");

    public static final ElementId GATEWAY_AWAIT_SIGNATURE = new ElementId("gateway_awaitSignature");

    public static final ElementId GATEWAY_BIKE_AVAILABLE = new ElementId("gateway_bikeAvailable");

    public static final ElementId GATEWAY_BIKE_SOURCE_JOIN = new ElementId("gateway_bikeSourceJoin");

    public static final ElementId GATEWAY_FORK = new ElementId("gateway_fork");

    public static final ElementId GATEWAY_IS_SOLVENT = new ElementId("gateway_isSolvent");

    public static final ElementId GATEWAY_JOIN = new ElementId("gateway_join");

    public static final ElementId GATEWAY_REJECTION_JOIN = new ElementId("gateway_rejectionJoin");

    public static final ElementId SERVICE_TASK_ACTIVATE_LEASING = new ElementId("serviceTask_activateLeasing");

    public static final ElementId SERVICE_TASK_CANCEL_CONTRACT = new ElementId("serviceTask_cancelContract");

    public static final ElementId SERVICE_TASK_CANCEL_POLICY = new ElementId("serviceTask_cancelPolicy");

    public static final ElementId SERVICE_TASK_ISSUE_INSURANCE_POLICY = new ElementId("serviceTask_issueInsurancePolicy");

    public static final ElementId SERVICE_TASK_ORDER_BIKE = new ElementId("serviceTask_orderBike");

    public static final ElementId SERVICE_TASK_SEND_CANCELLATION_CONFIRMATION = new ElementId("serviceTask_sendCancellationConfirmation");

    public static final ElementId SERVICE_TASK_SEND_CONTRACT = new ElementId("serviceTask_sendContract");

    public static final ElementId SERVICE_TASK_SEND_REJECTION = new ElementId("serviceTask_sendRejection");

    public static final ElementId SERVICE_TASK_SEND_REMINDER_MAIL = new ElementId("serviceTask_sendReminderMail");

    public static final ElementId SERVICE_TASK_VALIDATE_APPLICATION = new ElementId("serviceTask_validateApplication");

    public static final ElementId START_EVENT_APPLICATION_WITHDRAWN = new ElementId("startEvent_applicationWithdrawn");

    public static final ElementId START_EVENT_CUSTOMER_ELIGIBLE = new ElementId("startEvent_customerEligible");

    public static final ElementId START_EVENT_LEASING_REQUEST_RECEIVED = new ElementId("startEvent_leasingRequestReceived");

    public static final ElementId SUB_PROCESS_APPLICATION_WITHDRAWN = new ElementId("subProcess_applicationWithdrawn");

    public static final ElementId SUB_PROCESS_CONCLUDE_CONTRACT = new ElementId("subProcess_concludeContract");

    public static final ElementId USER_TASK_CLARIFY_ALTERNATIVE = new ElementId("userTask_clarifyAlternative");
  }

  /**
   * Call activities grouped by element. Each nested class exposes the called {@code PROCESS_ID} plus the variable mappings passed into ({@code Inputs}) and returned from ({@code Outputs}) the called process.
   */
  public static final class CallActivities {
    public static final class CallActivityCancelBikeOrder {
      public static final ProcessId PROCESS_ID = new ProcessId("cancelBikeOrder");

      public static final class Inputs {
        public static final InputOutputMapping BIKE_ID = new InputOutputMapping("bikeId", "bikeId", null);

        public static final InputOutputMapping ORDER_ID = new InputOutputMapping("orderId", "orderId", null);
      }
    }
  }

  /**
   * BPMN message names used to correlate messages to running process instances.
   */
  public static final class Messages {
    public static final MessageName MIRAVELO_APPLICATION_WITHDRAWN = new MessageName("miravelo.applicationWithdrawn");

    public static final MessageName MIRAVELO_CONTRACT_SIGNED = new MessageName("miravelo.contractSigned");

    public static final MessageName MIRAVELO_HANDOVER_REPORTED = new MessageName("miravelo.handoverReported");

    public static final MessageName MIRAVELO_LEASING_REQUEST_RECEIVED = new MessageName("miravelo.leasingRequestReceived");
  }

  /**
   * Job worker task types used in {@code @JobWorker(type = ServiceTasks.X)} annotations.
   * Kept as {@code public static final String} because annotation arguments must be compile-time constants.
   */
  public static final class ServiceTasks {
    public static final String BIKE_LEASING_ACTIVATE_LEASING = "bikeLeasing.activateLeasing";

    public static final String BIKE_LEASING_CANCEL_CONTRACT = "bikeLeasing.cancelContract";

    public static final String BIKE_LEASING_CANCEL_POLICY = "bikeLeasing.cancelPolicy";

    public static final String BIKE_LEASING_ISSUE_INSURANCE_POLICY = "bikeLeasing.issueInsurancePolicy";

    public static final String BIKE_LEASING_ORDER_BIKE = "bikeLeasing.orderBike";

    public static final String BIKE_LEASING_SEND_CANCELLATION_CONFIRMATION = "bikeLeasing.sendCancellationConfirmation";

    public static final String BIKE_LEASING_SEND_CONTRACT = "bikeLeasing.sendContract";

    public static final String BIKE_LEASING_SEND_REJECTION = "bikeLeasing.sendRejection";

    public static final String BIKE_LEASING_SEND_REMINDER_MAIL = "bikeLeasing.sendReminderMail";

    public static final String BIKE_LEASING_VALIDATE_APPLICATION = "bikeLeasing.validateApplication";
  }

  public static final class Timers {
    public static final BpmnTimer EVENT_SIGNATURE_DEADLINE = new BpmnTimer("Duration", "P14D");

    public static final BpmnTimer EVENT_SIGNATURE_REMINDER = new BpmnTimer("Duration", "P7D");

    public static final BpmnTimer EVENT_WITHDRAWAL_PERIOD_ELAPSED = new BpmnTimer("Duration", "P14D");
  }

  public static final class Errors {
    public static final BpmnError APPLICATION_INVALID = new BpmnError("Application_Invalid", "applicationInvalid");
  }

  public static final class Escalations {
    public static final BpmnEscalation CONTRACT_NOT_SIGNED = new BpmnEscalation("Contract_Not_Signed", "contractNotSigned");
  }

  public static final class Compensations {
    public static final ElementId EVENT_COMPENSATE_CONTRACT = new ElementId("event_compensateContract");

    public static final ElementId EVENT_COMPENSATE_INSURANCE = new ElementId("event_compensateInsurance");

    public static final ElementId EVENT_COMPENSATE_ORDER = new ElementId("event_compensateOrder");

    public static final ElementId EVENT_REVERSE_APPLICATION = new ElementId("event_reverseApplication");

    public static final ElementId EVENT_TRIGGER_REVERSAL = new ElementId("event_triggerReversal");
  }

  /**
   * Process variables grouped by the BPMN element that declares them.
   * Direction is encoded in each variable's wrapper type: {@code VariableName.Input}, {@code VariableName.Output}, or {@code VariableName.InOut} when the variable is both read and written by the same element.
   * Consumer APIs that take a specific subtype (for example, a method accepting {@code VariableName.Output}) get compile-time direction enforcement.
   */
  public static final class Variables {
    public static final class CallActivityCancelBikeOrder {
      public static final VariableName.Input BIKE_ID = new VariableName.Input("bikeId");

      public static final VariableName.Input ORDER_ID = new VariableName.Input("orderId");
    }

    public static final class ServiceTaskOrderBike {
      public static final VariableName.Output BIKE_AVAILABLE = new VariableName.Output("bikeAvailable");

      public static final VariableName.Output ORDER_ID = new VariableName.Output("orderId");
    }

    public static final class StartEventLeasingRequestReceived {
      public static final VariableName.Input AGE = new VariableName.Input("age");

      public static final VariableName.Input APPLICATION_ID = new VariableName.Input("applicationId");

      public static final VariableName.Input BIKE_ID = new VariableName.Input("bikeId");

      public static final VariableName.Input MONTHLY_NET_INCOME = new VariableName.Input("monthlyNetIncome");
    }

    public static final class UserTaskClarifyAlternative {
      public static final VariableName.Output ALTERNATIVE_FOUND = new VariableName.Output("alternativeFound");
    }
  }

  /**
   * Sequence flows between BPMN elements.
   * Mainly useful for process-model tooling, tests, and AI-agent consumers reasoning about the process shape.
   * Worker code typically does not need these.
   */
  public static final class Flows {
    public static final BpmnFlow FLOW_ACTIVATE_TO_ACTIVE = new BpmnFlow("flow_activateToActive", null, "serviceTask_activateLeasing", "endEvent_leasingActive", null, false);

    public static final BpmnFlow FLOW_ALTERNATIVE_FOUND = new BpmnFlow("flow_alternativeFound", "Yes", "gateway_alternativeFound", "gateway_bikeSourceJoin", null, true);

    public static final BpmnFlow FLOW_AWAIT_TO_DEADLINE = new BpmnFlow("flow_awaitToDeadline", null, "gateway_awaitSignature", "event_signatureDeadline", null, false);

    public static final BpmnFlow FLOW_AWAIT_TO_SIGNED = new BpmnFlow("flow_awaitToSigned", null, "gateway_awaitSignature", "event_contractSigned", null, false);

    public static final BpmnFlow FLOW_BIKE_AVAILABLE = new BpmnFlow("flow_bikeAvailable", "Yes", "gateway_bikeAvailable", "gateway_join", null, true);

    public static final BpmnFlow FLOW_BIKE_SOURCE_TO_ORDER = new BpmnFlow("flow_bikeSourceToOrder", null, "gateway_bikeSourceJoin", "serviceTask_orderBike", null, false);

    public static final BpmnFlow FLOW_BIKE_UNAVAILABLE = new BpmnFlow("flow_bikeUnavailable", "No", "gateway_bikeAvailable", "userTask_clarifyAlternative", "${!bikeAvailable}", false);

    public static final BpmnFlow FLOW_CLARIFY_TO_ALTERNATIVE_GATEWAY = new BpmnFlow("flow_clarifyToAlternativeGateway", null, "userTask_clarifyAlternative", "gateway_alternativeFound", null, false);

    public static final BpmnFlow FLOW_CONFIRMATION_TO_CANCELLED = new BpmnFlow("flow_confirmationToCancelled", null, "serviceTask_sendCancellationConfirmation", "endEvent_applicationCancelled", null, false);

    public static final BpmnFlow FLOW_CONTRACT_CONCLUDED_TO_FORK = new BpmnFlow("flow_contractConcludedToFork", null, "subProcess_concludeContract", "gateway_fork", null, false);

    public static final BpmnFlow FLOW_CONTRACT_SENT_TO_AWAIT = new BpmnFlow("flow_contractSentToAwait", null, "serviceTask_sendContract", "gateway_awaitSignature", null, false);

    public static final BpmnFlow FLOW_CREDIT_CHECK_TO_SOLVENCY = new BpmnFlow("flow_creditCheckToSolvency", null, "businessRuleTask_checkCreditRating", "gateway_isSolvent", null, false);

    public static final BpmnFlow FLOW_DEADLINE_TO_NOT_SIGNED = new BpmnFlow("flow_deadlineToNotSigned", null, "event_signatureDeadline", "endEvent_notSigned", null, false);

    public static final BpmnFlow FLOW_ELIGIBLE_TO_SEND_CONTRACT = new BpmnFlow("flow_eligibleToSendContract", null, "startEvent_customerEligible", "serviceTask_sendContract", null, false);

    public static final BpmnFlow FLOW_FORK_TO_BIKE_SOURCE = new BpmnFlow("flow_forkToBikeSource", null, "gateway_fork", "gateway_bikeSourceJoin", null, false);

    public static final BpmnFlow FLOW_FORK_TO_INSURANCE = new BpmnFlow("flow_forkToInsurance", null, "gateway_fork", "serviceTask_issueInsurancePolicy", null, false);

    public static final BpmnFlow FLOW_HANDOVER_TO_WITHDRAWAL_PERIOD = new BpmnFlow("flow_handoverToWithdrawalPeriod", null, "event_handoverReported", "event_withdrawalPeriodElapsed", null, false);

    public static final BpmnFlow FLOW_INSURANCE_TO_JOIN = new BpmnFlow("flow_insuranceToJoin", null, "serviceTask_issueInsurancePolicy", "gateway_join", null, false);

    public static final BpmnFlow FLOW_INVALID_TO_REJECTION = new BpmnFlow("flow_invalidToRejection", null, "event_applicationInvalid", "gateway_rejectionJoin", null, false);

    public static final BpmnFlow FLOW_JOIN_TO_HANDOVER = new BpmnFlow("flow_joinToHandover", null, "gateway_join", "event_handoverReported", null, false);

    public static final BpmnFlow FLOW_MAIL_TO_PROSPECT_REMINDED = new BpmnFlow("flow_mailToProspectReminded", null, "serviceTask_sendReminderMail", "endEvent_prospectReminded", null, false);

    public static final BpmnFlow FLOW_NO_ALTERNATIVE_FOUND = new BpmnFlow("flow_noAlternativeFound", "No", "gateway_alternativeFound", "event_triggerReversal", "${!alternativeFound}", false);

    public static final BpmnFlow FLOW_NOT_SIGNED_TO_REJECTION = new BpmnFlow("flow_notSignedToRejection", null, "event_contractNotSigned", "gateway_rejectionJoin", null, false);

    public static final BpmnFlow FLOW_NOT_SOLVENT = new BpmnFlow("flow_notSolvent", "No", "gateway_isSolvent", "gateway_rejectionJoin", "${!solvent}", false);

    public static final BpmnFlow FLOW_ORDERED_TO_BIKE_AVAILABLE = new BpmnFlow("flow_orderedToBikeAvailable", null, "serviceTask_orderBike", "gateway_bikeAvailable", null, false);

    public static final BpmnFlow FLOW_REJECTION_JOINED = new BpmnFlow("flow_rejectionJoined", null, "gateway_rejectionJoin", "serviceTask_sendRejection", null, false);

    public static final BpmnFlow FLOW_REJECTION_SENT = new BpmnFlow("flow_rejectionSent", null, "serviceTask_sendRejection", "endEvent_applicationRejected", null, false);

    public static final BpmnFlow FLOW_REMINDER_TO_MAIL = new BpmnFlow("flow_reminderToMail", null, "event_signatureReminder", "serviceTask_sendReminderMail", null, false);

    public static final BpmnFlow FLOW_REQUEST_TO_VALIDATION = new BpmnFlow("flow_requestToValidation", null, "startEvent_leasingRequestReceived", "serviceTask_validateApplication", null, false);

    public static final BpmnFlow FLOW_REVERSAL_TO_CONFIRMATION = new BpmnFlow("flow_reversalToConfirmation", null, "event_reverseApplication", "serviceTask_sendCancellationConfirmation", null, false);

    public static final BpmnFlow FLOW_REVERSAL_TO_CONTRACT_CANCELLED = new BpmnFlow("flow_reversalToContractCancelled", null, "event_triggerReversal", "endEvent_contractCancelled", null, false);

    public static final BpmnFlow FLOW_SIGNED_TO_CONTRACT_VALID = new BpmnFlow("flow_signedToContractValid", null, "event_contractSigned", "endEvent_contractValid", null, false);

    public static final BpmnFlow FLOW_SOLVENT = new BpmnFlow("flow_solvent", null, "gateway_isSolvent", "subProcess_concludeContract", null, true);

    public static final BpmnFlow FLOW_VALIDATED_TO_CREDIT_CHECK = new BpmnFlow("flow_validatedToCreditCheck", null, "serviceTask_validateApplication", "businessRuleTask_checkCreditRating", null, false);

    public static final BpmnFlow FLOW_WITHDRAWAL_ELAPSED_TO_ACTIVE = new BpmnFlow("flow_withdrawalElapsedToActive", null, "event_withdrawalPeriodElapsed", "serviceTask_activateLeasing", null, false);

    public static final BpmnFlow FLOW_WITHDRAWAL_TO_REVERSAL = new BpmnFlow("flow_withdrawalToReversal", null, "startEvent_applicationWithdrawn", "event_reverseApplication", null, false);
  }

  /**
   * Per-element graph metadata (elementType / previousElements / followingElements / parentId / boundary attachments).
   * Intended for tooling and tests, not worker runtime code.
   */
  public static final class Relations {
    public static final BpmnRelations BUSINESS_RULE_TASK_CHECK_CREDIT_RATING = new BpmnRelations("Check credit rating", List.of("serviceTask_validateApplication"), List.of("gateway_isSolvent"), null, null, List.of(), "BUSINESS_RULE_TASK");

    public static final BpmnRelations CALL_ACTIVITY_CANCEL_BIKE_ORDER = new BpmnRelations("Cancel bike order", List.of(), List.of(), null, null, List.of(), "CALL_ACTIVITY");

    public static final BpmnRelations END_EVENT_APPLICATION_CANCELLED = new BpmnRelations("Leasing cancelled", List.of("serviceTask_sendCancellationConfirmation"), List.of(), "subProcess_applicationWithdrawn", null, List.of(), "END_EVENT");

    public static final BpmnRelations END_EVENT_APPLICATION_REJECTED = new BpmnRelations("Application rejected", List.of("serviceTask_sendRejection"), List.of(), null, null, List.of(), "END_EVENT");

    public static final BpmnRelations END_EVENT_CONTRACT_CANCELLED = new BpmnRelations("Contract cancelled", List.of("event_triggerReversal"), List.of(), null, null, List.of(), "END_EVENT");

    public static final BpmnRelations END_EVENT_CONTRACT_VALID = new BpmnRelations("Contract valid", List.of("event_contractSigned"), List.of(), "subProcess_concludeContract", null, List.of(), "END_EVENT");

    public static final BpmnRelations END_EVENT_LEASING_ACTIVE = new BpmnRelations("Leasing active", List.of("serviceTask_activateLeasing"), List.of(), null, null, List.of(), "END_EVENT");

    public static final BpmnRelations END_EVENT_NOT_SIGNED = new BpmnRelations("Not signed", List.of("event_signatureDeadline"), List.of(), "subProcess_concludeContract", null, List.of(), "ESCALATION_END_EVENT");

    public static final BpmnRelations END_EVENT_PROSPECT_REMINDED = new BpmnRelations("Prospect reminded", List.of("serviceTask_sendReminderMail"), List.of(), null, null, List.of(), "END_EVENT");

    public static final BpmnRelations EVENT_APPLICATION_INVALID = new BpmnRelations("Application invalid", List.of(), List.of("gateway_rejectionJoin"), null, "serviceTask_validateApplication", List.of(), "ERROR_BOUNDARY_EVENT");

    public static final BpmnRelations EVENT_COMPENSATE_CONTRACT = new BpmnRelations("Compensate contract", List.of(), List.of(), null, "subProcess_concludeContract", List.of(), "COMPENSATION_BOUNDARY_EVENT");

    public static final BpmnRelations EVENT_COMPENSATE_INSURANCE = new BpmnRelations("Compensate policy", List.of(), List.of(), null, "serviceTask_issueInsurancePolicy", List.of(), "COMPENSATION_BOUNDARY_EVENT");

    public static final BpmnRelations EVENT_COMPENSATE_ORDER = new BpmnRelations("Compensate order", List.of(), List.of(), null, "serviceTask_orderBike", List.of(), "COMPENSATION_BOUNDARY_EVENT");

    public static final BpmnRelations EVENT_CONTRACT_NOT_SIGNED = new BpmnRelations("Contract not signed", List.of(), List.of("gateway_rejectionJoin"), null, "subProcess_concludeContract", List.of(), "ESCALATION_BOUNDARY_EVENT");

    public static final BpmnRelations EVENT_CONTRACT_SIGNED = new BpmnRelations("Contract signed", List.of("gateway_awaitSignature"), List.of("endEvent_contractValid"), "subProcess_concludeContract", null, List.of(), "MESSAGE_INTERMEDIATE_CATCH_EVENT");

    public static final BpmnRelations EVENT_HANDOVER_REPORTED = new BpmnRelations("Handover reported", List.of("gateway_join"), List.of("event_withdrawalPeriodElapsed"), null, null, List.of(), "MESSAGE_INTERMEDIATE_CATCH_EVENT");

    public static final BpmnRelations EVENT_REVERSE_APPLICATION = new BpmnRelations("Reverse application", List.of("startEvent_applicationWithdrawn"), List.of("serviceTask_sendCancellationConfirmation"), "subProcess_applicationWithdrawn", null, List.of(), "COMPENSATION_INTERMEDIATE_THROW_EVENT");

    public static final BpmnRelations EVENT_SIGNATURE_DEADLINE = new BpmnRelations("14 days", List.of("gateway_awaitSignature"), List.of("endEvent_notSigned"), "subProcess_concludeContract", null, List.of(), "TIMER_INTERMEDIATE_CATCH_EVENT");

    public static final BpmnRelations EVENT_SIGNATURE_REMINDER = new BpmnRelations("7 days", List.of(), List.of("serviceTask_sendReminderMail"), null, "subProcess_concludeContract", List.of(), "TIMER_BOUNDARY_EVENT");

    public static final BpmnRelations EVENT_TRIGGER_REVERSAL = new BpmnRelations("Trigger reversal", List.of("gateway_alternativeFound"), List.of("endEvent_contractCancelled"), null, null, List.of(), "COMPENSATION_INTERMEDIATE_THROW_EVENT");

    public static final BpmnRelations EVENT_WITHDRAWAL_PERIOD_ELAPSED = new BpmnRelations("Await end of withdrawal period", List.of("event_handoverReported"), List.of("serviceTask_activateLeasing"), null, null, List.of(), "TIMER_INTERMEDIATE_CATCH_EVENT");

    public static final BpmnRelations GATEWAY_ALTERNATIVE_FOUND = new BpmnRelations("Alternative found?", List.of("userTask_clarifyAlternative"), List.of("gateway_bikeSourceJoin", "event_triggerReversal"), null, null, List.of(), "EXCLUSIVE_GATEWAY");

    public static final BpmnRelations GATEWAY_AWAIT_SIGNATURE = new BpmnRelations(null, List.of("serviceTask_sendContract"), List.of("event_contractSigned", "event_signatureDeadline"), "subProcess_concludeContract", null, List.of(), "EVENT_BASED_GATEWAY");

    public static final BpmnRelations GATEWAY_BIKE_AVAILABLE = new BpmnRelations("Bike available?", List.of("serviceTask_orderBike"), List.of("gateway_join", "userTask_clarifyAlternative"), null, null, List.of(), "EXCLUSIVE_GATEWAY");

    public static final BpmnRelations GATEWAY_BIKE_SOURCE_JOIN = new BpmnRelations(null, List.of("gateway_fork", "gateway_alternativeFound"), List.of("serviceTask_orderBike"), null, null, List.of(), "EXCLUSIVE_GATEWAY");

    public static final BpmnRelations GATEWAY_FORK = new BpmnRelations(null, List.of("subProcess_concludeContract"), List.of("gateway_bikeSourceJoin", "serviceTask_issueInsurancePolicy"), null, null, List.of(), "PARALLEL_GATEWAY");

    public static final BpmnRelations GATEWAY_IS_SOLVENT = new BpmnRelations("Solvent?", List.of("businessRuleTask_checkCreditRating"), List.of("subProcess_concludeContract", "gateway_rejectionJoin"), null, null, List.of(), "EXCLUSIVE_GATEWAY");

    public static final BpmnRelations GATEWAY_JOIN = new BpmnRelations(null, List.of("serviceTask_issueInsurancePolicy", "gateway_bikeAvailable"), List.of("event_handoverReported"), null, null, List.of(), "PARALLEL_GATEWAY");

    public static final BpmnRelations GATEWAY_REJECTION_JOIN = new BpmnRelations("Rejection reason", List.of("event_applicationInvalid", "gateway_isSolvent", "event_contractNotSigned"), List.of("serviceTask_sendRejection"), null, null, List.of(), "EXCLUSIVE_GATEWAY");

    public static final BpmnRelations SERVICE_TASK_ACTIVATE_LEASING = new BpmnRelations("Activate leasing", List.of("event_withdrawalPeriodElapsed"), List.of("endEvent_leasingActive"), null, null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations SERVICE_TASK_CANCEL_CONTRACT = new BpmnRelations("Cancel contract", List.of(), List.of(), null, null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations SERVICE_TASK_CANCEL_POLICY = new BpmnRelations("Cancel policy", List.of(), List.of(), null, null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations SERVICE_TASK_ISSUE_INSURANCE_POLICY = new BpmnRelations("Issue insurance policy", List.of("gateway_fork"), List.of("gateway_join"), null, null, List.of("event_compensateInsurance"), "SERVICE_TASK");

    public static final BpmnRelations SERVICE_TASK_ORDER_BIKE = new BpmnRelations("Order bike from dealer", List.of("gateway_bikeSourceJoin"), List.of("gateway_bikeAvailable"), null, null, List.of("event_compensateOrder"), "SERVICE_TASK");

    public static final BpmnRelations SERVICE_TASK_SEND_CANCELLATION_CONFIRMATION = new BpmnRelations("Send cancellation confirmation", List.of("event_reverseApplication"), List.of("endEvent_applicationCancelled"), "subProcess_applicationWithdrawn", null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations SERVICE_TASK_SEND_CONTRACT = new BpmnRelations("Send contract", List.of("startEvent_customerEligible"), List.of("gateway_awaitSignature"), "subProcess_concludeContract", null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations SERVICE_TASK_SEND_REJECTION = new BpmnRelations("Send rejection", List.of("gateway_rejectionJoin"), List.of("endEvent_applicationRejected"), null, null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations SERVICE_TASK_SEND_REMINDER_MAIL = new BpmnRelations("Send reminder mail", List.of("event_signatureReminder"), List.of("endEvent_prospectReminded"), null, null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations SERVICE_TASK_VALIDATE_APPLICATION = new BpmnRelations("Validate application", List.of("startEvent_leasingRequestReceived"), List.of("businessRuleTask_checkCreditRating"), null, null, List.of("event_applicationInvalid"), "SERVICE_TASK");

    public static final BpmnRelations START_EVENT_APPLICATION_WITHDRAWN = new BpmnRelations("Request withdrawn", List.of(), List.of("event_reverseApplication"), "subProcess_applicationWithdrawn", null, List.of(), "MESSAGE_START_EVENT");

    public static final BpmnRelations START_EVENT_CUSTOMER_ELIGIBLE = new BpmnRelations("Customer eligible", List.of(), List.of("serviceTask_sendContract"), "subProcess_concludeContract", null, List.of(), "START_EVENT");

    public static final BpmnRelations START_EVENT_LEASING_REQUEST_RECEIVED = new BpmnRelations("Leasing request received", List.of(), List.of("serviceTask_validateApplication"), null, null, List.of(), "MESSAGE_START_EVENT");

    public static final BpmnRelations SUB_PROCESS_APPLICATION_WITHDRAWN = new BpmnRelations("Application withdrawn", List.of(), List.of(), null, null, List.of(), "EVENT_SUB_PROCESS");

    public static final BpmnRelations SUB_PROCESS_CONCLUDE_CONTRACT = new BpmnRelations("Conclude contract", List.of("gateway_isSolvent"), List.of("gateway_fork"), null, null, List.of("event_compensateContract", "event_contractNotSigned", "event_signatureReminder"), "SUB_PROCESS");

    public static final BpmnRelations USER_TASK_CLARIFY_ALTERNATIVE = new BpmnRelations("Clarify alternative with customer", List.of("gateway_bikeAvailable"), List.of("gateway_alternativeFound"), null, null, List.of(), "USER_TASK");
  }
}
