// Generated by bpmn-to-code
package io.miragon.blueprint.process;

import io.miragon.bpmn.runtime.BpmnEngine;
import io.miragon.bpmn.runtime.BpmnFlow;
import io.miragon.bpmn.runtime.BpmnRelations;
import io.miragon.bpmn.runtime.ElementId;
import io.miragon.bpmn.runtime.ProcessId;
import io.miragon.bpmn.runtime.VariableName;
import java.lang.String;
import java.util.List;

public final class CancelBikeOrderProcessApi {
  public static final ProcessId PROCESS_ID = new ProcessId("cancelBikeOrder");

  public static final BpmnEngine PROCESS_ENGINE = BpmnEngine.CAMUNDA_7;

  /**
   * BPMN element ids as declared in the source model.
   * Typically used in process-level tests or when searching for tasks.
   * Worker runtime code rarely needs these.
   */
  public static final class Elements {
    public static final ElementId END_EVENT_ORDER_REVERSED = new ElementId("endEvent_orderReversed");

    public static final ElementId GATEWAY_CANCELLATION_POSSIBLE = new ElementId("gateway_cancellationPossible");

    public static final ElementId GATEWAY_JOIN = new ElementId("gateway_join");

    public static final ElementId SERVICE_TASK_BOOK_COSTS = new ElementId("serviceTask_bookCosts");

    public static final ElementId SERVICE_TASK_REQUEST_CANCELLATION = new ElementId("serviceTask_requestCancellation");

    public static final ElementId START_EVENT_CANCELLATION_REQUIRED = new ElementId("startEvent_cancellationRequired");

    public static final ElementId USER_TASK_CLARIFY_RETURN = new ElementId("userTask_clarifyReturn");
  }

  /**
   * Job worker task types used in {@code @JobWorker(type = ServiceTasks.X)} annotations.
   * Kept as {@code public static final String} because annotation arguments must be compile-time constants.
   */
  public static final class ServiceTasks {
    public static final String BIKE_LEASING_BOOK_COSTS = "bikeLeasing.bookCosts";

    public static final String BIKE_LEASING_REQUEST_CANCELLATION = "bikeLeasing.requestCancellation";
  }

  /**
   * Process variables grouped by the BPMN element that declares them.
   * Direction is encoded in each variable's wrapper type: {@code VariableName.Input}, {@code VariableName.Output}, or {@code VariableName.InOut} when the variable is both read and written by the same element.
   * Consumer APIs that take a specific subtype (for example, a method accepting {@code VariableName.Output}) get compile-time direction enforcement.
   */
  public static final class Variables {
    public static final class ServiceTaskRequestCancellation {
      public static final VariableName.Output CANCELLATION_POSSIBLE = new VariableName.Output("cancellationPossible");
    }

    public static final class StartEventCancellationRequired {
      public static final VariableName.Input BIKE_ID = new VariableName.Input("bikeId");

      public static final VariableName.Input ORDER_ID = new VariableName.Input("orderId");
    }
  }

  /**
   * Sequence flows between BPMN elements.
   * Mainly useful for process-model tooling, tests, and AI-agent consumers reasoning about the process shape.
   * Worker code typically does not need these.
   */
  public static final class Flows {
    public static final BpmnFlow FLOW_BOOK_COSTS_TO_JOIN = new BpmnFlow("flow_bookCostsToJoin", null, "serviceTask_bookCosts", "gateway_join", null, false);

    public static final BpmnFlow FLOW_CANCELLATION_NOT_POSSIBLE = new BpmnFlow("flow_cancellationNotPossible", "No", "gateway_cancellationPossible", "userTask_clarifyReturn", "${cancellationPossible}", false);

    public static final BpmnFlow FLOW_CANCELLATION_POSSIBLE = new BpmnFlow("flow_cancellationPossible", "Yes", "gateway_cancellationPossible", "gateway_join", null, true);

    public static final BpmnFlow FLOW_CLARIFY_TO_BOOK_COSTS = new BpmnFlow("flow_clarifyToBookCosts", null, "userTask_clarifyReturn", "serviceTask_bookCosts", null, false);

    public static final BpmnFlow FLOW_JOIN_TO_REVERSED = new BpmnFlow("flow_joinToReversed", null, "gateway_join", "endEvent_orderReversed", null, false);

    public static final BpmnFlow FLOW_REQUEST_TO_POSSIBLE_GATEWAY = new BpmnFlow("flow_requestToPossibleGateway", null, "serviceTask_requestCancellation", "gateway_cancellationPossible", null, false);

    public static final BpmnFlow FLOW_REQUIRED_TO_REQUEST = new BpmnFlow("flow_requiredToRequest", null, "startEvent_cancellationRequired", "serviceTask_requestCancellation", null, false);
  }

  /**
   * Per-element graph metadata (elementType / previousElements / followingElements / parentId / boundary attachments).
   * Intended for tooling and tests, not worker runtime code.
   */
  public static final class Relations {
    public static final BpmnRelations END_EVENT_ORDER_REVERSED = new BpmnRelations("Order reversed", List.of("gateway_join"), List.of(), null, null, List.of(), "END_EVENT");

    public static final BpmnRelations GATEWAY_CANCELLATION_POSSIBLE = new BpmnRelations("Cancellation possible?", List.of("serviceTask_requestCancellation"), List.of("userTask_clarifyReturn", "gateway_join"), null, null, List.of(), "EXCLUSIVE_GATEWAY");

    public static final BpmnRelations GATEWAY_JOIN = new BpmnRelations(null, List.of("gateway_cancellationPossible", "serviceTask_bookCosts"), List.of("endEvent_orderReversed"), null, null, List.of(), "EXCLUSIVE_GATEWAY");

    public static final BpmnRelations SERVICE_TASK_BOOK_COSTS = new BpmnRelations("Book costs", List.of("userTask_clarifyReturn"), List.of("gateway_join"), null, null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations SERVICE_TASK_REQUEST_CANCELLATION = new BpmnRelations("Request cancellation", List.of("startEvent_cancellationRequired"), List.of("gateway_cancellationPossible"), null, null, List.of(), "SERVICE_TASK");

    public static final BpmnRelations START_EVENT_CANCELLATION_REQUIRED = new BpmnRelations("Cancellation required", List.of(), List.of("serviceTask_requestCancellation"), null, null, List.of(), "START_EVENT");

    public static final BpmnRelations USER_TASK_CLARIFY_RETURN = new BpmnRelations("Clarify return with supplier", List.of("gateway_cancellationPossible"), List.of("serviceTask_bookCosts"), null, null, List.of(), "USER_TASK");
  }
}
