// Generated by bpmn-to-code
package io.miragon.blueprint.process;

import java.util.List;

/**
 * Job worker task types used in {@code @JobWorker(type = ServiceTasks.X)} annotations.
 * Kept as {@code public static final String} because annotation arguments must be compile-time constants.
 */
public final class ServiceTasks {
  public static final String BIKE_LEASING_ACTIVATE_LEASING = "bikeLeasing.activateLeasing";

  public static final String BIKE_LEASING_BOOK_COSTS = "bikeLeasing.bookCosts";

  public static final String BIKE_LEASING_CANCEL_CONTRACT = "bikeLeasing.cancelContract";

  public static final String BIKE_LEASING_CANCEL_POLICY = "bikeLeasing.cancelPolicy";

  public static final String BIKE_LEASING_ISSUE_INSURANCE_POLICY = "bikeLeasing.issueInsurancePolicy";

  public static final String BIKE_LEASING_ORDER_BIKE = "bikeLeasing.orderBike";

  public static final String BIKE_LEASING_REQUEST_CANCELLATION = "bikeLeasing.requestCancellation";

  public static final String BIKE_LEASING_SEND_CANCELLATION_CONFIRMATION = "bikeLeasing.sendCancellationConfirmation";

  public static final String BIKE_LEASING_SEND_CONTRACT = "bikeLeasing.sendContract";

  public static final String BIKE_LEASING_SEND_REJECTION = "bikeLeasing.sendRejection";

  public static final String BIKE_LEASING_SEND_REMINDER_MAIL = "bikeLeasing.sendReminderMail";

  private ServiceTasks() {
  }

  public static List<String> all() {
    return List.of(
        BIKE_LEASING_ACTIVATE_LEASING,
        BIKE_LEASING_BOOK_COSTS,
        BIKE_LEASING_CANCEL_CONTRACT,
        BIKE_LEASING_CANCEL_POLICY,
        BIKE_LEASING_ISSUE_INSURANCE_POLICY,
        BIKE_LEASING_ORDER_BIKE,
        BIKE_LEASING_REQUEST_CANCELLATION,
        BIKE_LEASING_SEND_CANCELLATION_CONFIRMATION,
        BIKE_LEASING_SEND_CONTRACT,
        BIKE_LEASING_SEND_REJECTION,
        BIKE_LEASING_SEND_REMINDER_MAIL);
  }
}
