package io.miragon.blueprint.adapter.outbound.engine

import io.miragon.blueprint.application.port.outbound.LeasingProcess
import io.miragon.blueprint.domain.bike.BikeId
import io.miragon.blueprint.domain.leasing.ApplicationId
import io.miragon.blueprint.domain.leasing.LeasingApplication
import io.miragon.blueprint.process.BikeLeasingProcessProcessApi.FlowNodes
import io.miragon.blueprint.process.Messages
import mu.KotlinLogging
import org.operaton.rest.client.api.MessageApi
import org.operaton.rest.client.api.TaskApi
import org.operaton.rest.client.model.CompleteTaskDto
import org.operaton.rest.client.model.CorrelationMessageDto
import org.operaton.rest.client.model.VariableValueDto
import org.springframework.stereotype.Component

/**
 * Drives the *remote* Operaton engine over its REST API (`/engine-rest`): starts the process via its
 * message start event, correlates the messages that release the wait states, and completes the
 * alternative-clarification user task from the outside. The service-tasks are handled separately via
 * the external-task client.
 *
 * The REST calls go through the **autogenerated** Operaton client ([MessageApi], [TaskApi]) from
 * `common-operaton-client`, so URIs, request/response shapes and the typed-variable payload are typed
 * rather than hand-built. As in the embedded blueprint, the [ApplicationId] is used as the **process
 * business key**, so messages and user-task lookups correlate to the right instance by business key.
 * Variable and element names come from the typed process API this service generates from its own
 * `bike-leasing.bpmn`.
 */
@Component
class RemoteLeasingProcessAdapter(
    private val messageApi: MessageApi,
    private val taskApi: TaskApi,
) : LeasingProcess {

    private val log = KotlinLogging.logger {}

    override fun submitRequest(application: LeasingApplication) {
        val start = FlowNodes.StartEventLeasingRequestReceived.Variables
        messageApi.deliverMessageWithHttpInfo(
            CorrelationMessageDto(
                messageName = Messages.MIRAVELO_LEASING_REQUEST_RECEIVED.value,
                businessKey = application.id.value.toString(),
                processVariables = mapOf(
                    start.APPLICATION_ID.value to typedVar(application.id.value.toString()),
                    start.BIKE_ID.value to typedVar(application.bikeId.value),
                    start.MONTHLY_NET_INCOME.value to typedVar(application.monthlyNetIncome),
                    start.AGE.value to typedVar(application.age),
                ),
            ),
        )
        log.info { "Started remote leasing process for application ${application.id.value}" }
    }

    override fun correlateContractSigned(id: ApplicationId) =
        correlateByBusinessKey(Messages.MIRAVELO_CONTRACT_SIGNED.value, id)

    override fun correlateHandoverReported(id: ApplicationId) =
        correlateByBusinessKey(Messages.MIRAVELO_HANDOVER_REPORTED.value, id)

    override fun correlateApplicationWithdrawn(id: ApplicationId) =
        correlateByBusinessKey(Messages.MIRAVELO_APPLICATION_WITHDRAWN.value, id)

    /**
     * Completes the `Clarify alternative with customer` user task via the engine's REST API — the same
     * task a human could complete through its deployed Camunda Form in the Tasklist.
     */
    override fun completeAlternativeClarification(
        id: ApplicationId,
        alternativeFound: Boolean,
        bikeId: BikeId?,
    ) {
        val taskId = findTaskId(id, FlowNodes.UserTaskClarifyAlternative.id.value)
        val variables = buildMap {
            put(FlowNodes.UserTaskClarifyAlternative.Variables.ALTERNATIVE_FOUND.value, typedVar(alternativeFound))
            // The re-order reads the same start-injected bike variable, so reuse its name.
            bikeId?.let { put(FlowNodes.StartEventLeasingRequestReceived.Variables.BIKE_ID.value, typedVar(it.value)) }
        }
        taskApi.completeWithHttpInfo(taskId, CompleteTaskDto(variables = variables))
        log.info { "Completed clarify-alternative task ($taskId) for application ${id.value}" }
    }

    private fun correlateByBusinessKey(messageName: String, id: ApplicationId) {
        messageApi.deliverMessageWithHttpInfo(
            CorrelationMessageDto(messageName = messageName, businessKey = id.value.toString()),
        )
        log.info { "Correlated '$messageName' to application ${id.value}" }
    }

    private fun findTaskId(id: ApplicationId, taskDefinitionKey: String): String {
        val tasks = taskApi.getTasks(
            processInstanceBusinessKey = id.value.toString(),
            taskDefinitionKey = taskDefinitionKey,
        )
        return tasks.firstOrNull()?.id
            ?: error("No active task '$taskDefinitionKey' found for application ${id.value}")
    }

    /** Wraps a Kotlin value as the engine's typed process-variable payload (`{ value, type }`). */
    private fun typedVar(value: Any?): VariableValueDto {
        val type = when (value) {
            is String -> "String"
            is Boolean -> "Boolean"
            is Int -> "Integer"
            is Long -> "Long"
            is Double -> "Double"
            null -> "Null"
            else -> error("Unsupported process-variable type: ${value::class}")
        }
        return VariableValueDto(value = value, type = type)
    }
}
